// Code generated by protoc-gen-go.
// source: ipc_push.proto
// DO NOT EDIT!

/*
Package protol is a generated protocol buffer package.

It is generated from these files:
	ipc_push.proto

It has these top-level messages:
	DevOnline
	DevOffline
	DevAlive
	PushDataReq
	PushDataRes
	PushBatchReq
	PushBatchRes
	PushDeviceReq
	PushDeviceRes
*/
package protol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ResultType int32

const (
	ResultType_SUCCEED ResultType = 0
	ResultType_FAILED  ResultType = -1
)

var ResultType_name = map[int32]string{
	0:  "SUCCEED",
	-1: "FAILED",
}
var ResultType_value = map[string]int32{
	"SUCCEED": 0,
	"FAILED":  -1,
}

func (x ResultType) Enum() *ResultType {
	p := new(ResultType)
	*p = x
	return p
}
func (x ResultType) String() string {
	return proto.EnumName(ResultType_name, int32(x))
}
func (x *ResultType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ResultType_value, data, "ResultType")
	if err != nil {
		return err
	}
	*x = ResultType(value)
	return nil
}
func (ResultType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type DevOnline struct {
	Duid             *int64 `protobuf:"varint,1,req,name=duid" json:"duid,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *DevOnline) Reset()                    { *m = DevOnline{} }
func (m *DevOnline) String() string            { return proto.CompactTextString(m) }
func (*DevOnline) ProtoMessage()               {}
func (*DevOnline) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DevOnline) GetDuid() int64 {
	if m != nil && m.Duid != nil {
		return *m.Duid
	}
	return 0
}

type DevOffline struct {
	Duid             *int64 `protobuf:"varint,1,req,name=duid" json:"duid,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *DevOffline) Reset()                    { *m = DevOffline{} }
func (m *DevOffline) String() string            { return proto.CompactTextString(m) }
func (*DevOffline) ProtoMessage()               {}
func (*DevOffline) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DevOffline) GetDuid() int64 {
	if m != nil && m.Duid != nil {
		return *m.Duid
	}
	return 0
}

type DevAlive struct {
	Duid             []int64 `protobuf:"varint,1,rep,name=duid" json:"duid,omitempty"`
	NetTimeSec       *int32  `protobuf:"varint,2,req,name=net_time_sec,json=netTimeSec" json:"net_time_sec,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DevAlive) Reset()                    { *m = DevAlive{} }
func (m *DevAlive) String() string            { return proto.CompactTextString(m) }
func (*DevAlive) ProtoMessage()               {}
func (*DevAlive) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *DevAlive) GetDuid() []int64 {
	if m != nil {
		return m.Duid
	}
	return nil
}

func (m *DevAlive) GetNetTimeSec() int32 {
	if m != nil && m.NetTimeSec != nil {
		return *m.NetTimeSec
	}
	return 0
}

type PushDataReq struct {
	Duid             *int64  `protobuf:"varint,1,req,name=duid" json:"duid,omitempty"`
	MsgData          *string `protobuf:"bytes,2,req,name=msg_data,json=msgData" json:"msg_data,omitempty"`
	ExpireTime       *int32  `protobuf:"varint,3,req,name=expire_time,json=expireTime" json:"expire_time,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PushDataReq) Reset()                    { *m = PushDataReq{} }
func (m *PushDataReq) String() string            { return proto.CompactTextString(m) }
func (*PushDataReq) ProtoMessage()               {}
func (*PushDataReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PushDataReq) GetDuid() int64 {
	if m != nil && m.Duid != nil {
		return *m.Duid
	}
	return 0
}

func (m *PushDataReq) GetMsgData() string {
	if m != nil && m.MsgData != nil {
		return *m.MsgData
	}
	return ""
}

func (m *PushDataReq) GetExpireTime() int32 {
	if m != nil && m.ExpireTime != nil {
		return *m.ExpireTime
	}
	return 0
}

// 外部服务调用rpc协议
type PushDataRes struct {
	Result           *ResultType `protobuf:"varint,2,req,name=result,enum=protol.ResultType" json:"result,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *PushDataRes) Reset()                    { *m = PushDataRes{} }
func (m *PushDataRes) String() string            { return proto.CompactTextString(m) }
func (*PushDataRes) ProtoMessage()               {}
func (*PushDataRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *PushDataRes) GetResult() ResultType {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return ResultType_SUCCEED
}

type PushBatchReq struct {
	PushBatchs       []*PushDataReq `protobuf:"bytes,1,rep,name=push_batchs,json=pushBatchs" json:"push_batchs,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *PushBatchReq) Reset()                    { *m = PushBatchReq{} }
func (m *PushBatchReq) String() string            { return proto.CompactTextString(m) }
func (*PushBatchReq) ProtoMessage()               {}
func (*PushBatchReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *PushBatchReq) GetPushBatchs() []*PushDataReq {
	if m != nil {
		return m.PushBatchs
	}
	return nil
}

type PushBatchRes struct {
	Result           *ResultType `protobuf:"varint,2,req,name=result,enum=protol.ResultType" json:"result,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *PushBatchRes) Reset()                    { *m = PushBatchRes{} }
func (m *PushBatchRes) String() string            { return proto.CompactTextString(m) }
func (*PushBatchRes) ProtoMessage()               {}
func (*PushBatchRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *PushBatchRes) GetResult() ResultType {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return ResultType_SUCCEED
}

// 推送给设备的信息
type PushDeviceReq struct {
	Duid             *int64  `protobuf:"varint,1,req,name=duid" json:"duid,omitempty"`
	MsgId            *int32  `protobuf:"varint,2,req,name=msg_id,json=msgId" json:"msg_id,omitempty"`
	MsgData          *string `protobuf:"bytes,3,req,name=msg_data,json=msgData" json:"msg_data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PushDeviceReq) Reset()                    { *m = PushDeviceReq{} }
func (m *PushDeviceReq) String() string            { return proto.CompactTextString(m) }
func (*PushDeviceReq) ProtoMessage()               {}
func (*PushDeviceReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *PushDeviceReq) GetDuid() int64 {
	if m != nil && m.Duid != nil {
		return *m.Duid
	}
	return 0
}

func (m *PushDeviceReq) GetMsgId() int32 {
	if m != nil && m.MsgId != nil {
		return *m.MsgId
	}
	return 0
}

func (m *PushDeviceReq) GetMsgData() string {
	if m != nil && m.MsgData != nil {
		return *m.MsgData
	}
	return ""
}

type PushDeviceRes struct {
	Duid             *int64 `protobuf:"varint,1,req,name=duid" json:"duid,omitempty"`
	MsgId            *int32 `protobuf:"varint,2,req,name=msg_id,json=msgId" json:"msg_id,omitempty"`
	Result           *int32 `protobuf:"varint,3,req,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PushDeviceRes) Reset()                    { *m = PushDeviceRes{} }
func (m *PushDeviceRes) String() string            { return proto.CompactTextString(m) }
func (*PushDeviceRes) ProtoMessage()               {}
func (*PushDeviceRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *PushDeviceRes) GetDuid() int64 {
	if m != nil && m.Duid != nil {
		return *m.Duid
	}
	return 0
}

func (m *PushDeviceRes) GetMsgId() int32 {
	if m != nil && m.MsgId != nil {
		return *m.MsgId
	}
	return 0
}

func (m *PushDeviceRes) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*DevOnline)(nil), "protol.DevOnline")
	proto.RegisterType((*DevOffline)(nil), "protol.DevOffline")
	proto.RegisterType((*DevAlive)(nil), "protol.DevAlive")
	proto.RegisterType((*PushDataReq)(nil), "protol.PushDataReq")
	proto.RegisterType((*PushDataRes)(nil), "protol.PushDataRes")
	proto.RegisterType((*PushBatchReq)(nil), "protol.PushBatchReq")
	proto.RegisterType((*PushBatchRes)(nil), "protol.PushBatchRes")
	proto.RegisterType((*PushDeviceReq)(nil), "protol.PushDeviceReq")
	proto.RegisterType((*PushDeviceRes)(nil), "protol.PushDeviceRes")
	proto.RegisterEnum("protol.ResultType", ResultType_name, ResultType_value)
}

func init() { proto.RegisterFile("ipc_push.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 338 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x90, 0xcf, 0x4f, 0xea, 0x40,
	0x10, 0x80, 0x1f, 0xf4, 0x51, 0x60, 0x8a, 0x84, 0x2c, 0xd1, 0xe0, 0x89, 0x66, 0x4f, 0x84, 0x03,
	0x07, 0xe2, 0x45, 0x4f, 0x22, 0xc5, 0x84, 0xc4, 0x44, 0xb3, 0xc0, 0xd1, 0x34, 0xb5, 0x1d, 0x60,
	0x93, 0xb6, 0x54, 0x76, 0xdb, 0xe8, 0x5f, 0xaf, 0xd9, 0x2d, 0x55, 0x9a, 0xc8, 0x81, 0x5e, 0xda,
	0xce, 0x8f, 0x6f, 0x66, 0x3e, 0x68, 0xf3, 0xc4, 0x77, 0x93, 0x54, 0x6c, 0x47, 0xc9, 0x7e, 0x27,
	0x77, 0xc4, 0xd4, 0xaf, 0x90, 0xf6, 0xa1, 0xe9, 0x60, 0xf6, 0x1c, 0x87, 0x3c, 0x46, 0x42, 0xe0,
	0x7f, 0x90, 0xf2, 0xa0, 0x57, 0xb1, 0xab, 0x03, 0x83, 0xe9, 0x6f, 0x6a, 0x03, 0xa8, 0x82, 0xf5,
	0xfa, 0x64, 0xc5, 0x3d, 0x34, 0x1c, 0xcc, 0x26, 0x21, 0xcf, 0x8e, 0xf3, 0x46, 0x91, 0x27, 0x36,
	0xb4, 0x62, 0x94, 0xae, 0xe4, 0x11, 0xba, 0x02, 0xfd, 0x5e, 0xd5, 0xae, 0x0e, 0x6a, 0x0c, 0x62,
	0x94, 0x4b, 0x1e, 0xe1, 0x02, 0x7d, 0xfa, 0x0a, 0xd6, 0x4b, 0x2a, 0xb6, 0x8e, 0x27, 0x3d, 0x86,
	0xef, 0x7f, 0x0d, 0x21, 0xd7, 0xd0, 0x88, 0xc4, 0xc6, 0x0d, 0x3c, 0xe9, 0x69, 0x40, 0x93, 0xd5,
	0x23, 0xb1, 0x51, 0x1d, 0xa4, 0x0f, 0x16, 0x7e, 0x24, 0x7c, 0x8f, 0x7a, 0x44, 0xcf, 0xc8, 0xf1,
	0x79, 0x48, 0x4d, 0xa0, 0xb7, 0xc7, 0x78, 0x41, 0x86, 0x60, 0xee, 0x51, 0xa4, 0xa1, 0xd4, 0xa0,
	0xf6, 0x98, 0xe4, 0x4a, 0xc2, 0x11, 0xd3, 0xd1, 0xe5, 0x67, 0x82, 0xec, 0x50, 0x41, 0x1d, 0x68,
	0xa9, 0xd6, 0x07, 0x4f, 0xfa, 0x5b, 0xb5, 0xda, 0x0d, 0x58, 0x4a, 0xa2, 0xfb, 0xa6, 0x02, 0x42,
	0x9f, 0x69, 0x8d, 0xbb, 0x05, 0xe0, 0xe8, 0x08, 0x06, 0x49, 0xd1, 0x27, 0xe8, 0x5d, 0x89, 0x72,
	0xde, 0x06, 0x2b, 0xb8, 0xd0, 0x58, 0xcc, 0xb8, 0x8f, 0xa7, 0xec, 0x5c, 0x82, 0xa9, 0xec, 0xf0,
	0xe0, 0x20, 0xb7, 0x16, 0x89, 0xcd, 0xbc, 0x2c, 0xcd, 0x28, 0x49, 0xa3, 0xac, 0x8c, 0x15, 0xe7,
	0x60, 0xaf, 0x7e, 0xd6, 0xcf, 0x5d, 0x1f, 0xfe, 0x86, 0x23, 0x80, 0xdf, 0x03, 0x88, 0x05, 0xf5,
	0xc5, 0x6a, 0x3a, 0x9d, 0xcd, 0x9c, 0xce, 0x3f, 0xd2, 0x05, 0xf3, 0x71, 0x32, 0x7f, 0x9a, 0x39,
	0x9d, 0xaf, 0xe2, 0xa9, 0x7c, 0x07, 0x00, 0x00, 0xff, 0xff, 0x92, 0x6c, 0x41, 0x25, 0x94, 0x02,
	0x00, 0x00,
}
