// Code generated by protoc-gen-go.
// source: ipc_push.proto
// DO NOT EDIT!

/*
Package protol is a generated protocol buffer package.

It is generated from these files:
	ipc_push.proto

It has these top-level messages:
	DevStat
	DevOffline
	DevOnline
	DevsAlive
	DataOccur
	DataReq
	DataRes
	DataResBatchs
	PushDeviceReq
	PushDeviceRes
	PushDevBatchsReq
	PushDevBatchsRes
*/
package protol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DevStat struct {
	Duid             *string `protobuf:"bytes,1,req,name=duid" json:"duid,omitempty"`
	LastMsgId        *int64  `protobuf:"varint,2,req,name=last_msg_id,json=lastMsgId" json:"last_msg_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DevStat) Reset()                    { *m = DevStat{} }
func (m *DevStat) String() string            { return proto.CompactTextString(m) }
func (*DevStat) ProtoMessage()               {}
func (*DevStat) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DevStat) GetDuid() string {
	if m != nil && m.Duid != nil {
		return *m.Duid
	}
	return ""
}

func (m *DevStat) GetLastMsgId() int64 {
	if m != nil && m.LastMsgId != nil {
		return *m.LastMsgId
	}
	return 0
}

type DevOffline struct {
	Duid             *string `protobuf:"bytes,1,req,name=duid" json:"duid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DevOffline) Reset()                    { *m = DevOffline{} }
func (m *DevOffline) String() string            { return proto.CompactTextString(m) }
func (*DevOffline) ProtoMessage()               {}
func (*DevOffline) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DevOffline) GetDuid() string {
	if m != nil && m.Duid != nil {
		return *m.Duid
	}
	return ""
}

type DevOnline struct {
	Duid             *string `protobuf:"bytes,1,req,name=duid" json:"duid,omitempty"`
	LastMsgId        *int64  `protobuf:"varint,2,req,name=last_msg_id,json=lastMsgId" json:"last_msg_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DevOnline) Reset()                    { *m = DevOnline{} }
func (m *DevOnline) String() string            { return proto.CompactTextString(m) }
func (*DevOnline) ProtoMessage()               {}
func (*DevOnline) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *DevOnline) GetDuid() string {
	if m != nil && m.Duid != nil {
		return *m.Duid
	}
	return ""
}

func (m *DevOnline) GetLastMsgId() int64 {
	if m != nil && m.LastMsgId != nil {
		return *m.LastMsgId
	}
	return 0
}

type DevsAlive struct {
	DevOnline        []*DevStat `protobuf:"bytes,1,rep,name=dev_online,json=devOnline" json:"dev_online,omitempty"`
	NetTimeSec       *int32     `protobuf:"varint,2,req,name=net_time_sec,json=netTimeSec" json:"net_time_sec,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *DevsAlive) Reset()                    { *m = DevsAlive{} }
func (m *DevsAlive) String() string            { return proto.CompactTextString(m) }
func (*DevsAlive) ProtoMessage()               {}
func (*DevsAlive) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *DevsAlive) GetDevOnline() []*DevStat {
	if m != nil {
		return m.DevOnline
	}
	return nil
}

func (m *DevsAlive) GetNetTimeSec() int32 {
	if m != nil && m.NetTimeSec != nil {
		return *m.NetTimeSec
	}
	return 0
}

type DataOccur struct {
	Duid             *string `protobuf:"bytes,1,req,name=duid" json:"duid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DataOccur) Reset()                    { *m = DataOccur{} }
func (m *DataOccur) String() string            { return proto.CompactTextString(m) }
func (*DataOccur) ProtoMessage()               {}
func (*DataOccur) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *DataOccur) GetDuid() string {
	if m != nil && m.Duid != nil {
		return *m.Duid
	}
	return ""
}

type DataReq struct {
	Duid             *string `protobuf:"bytes,1,req,name=duid" json:"duid,omitempty"`
	LatMsgId         *int64  `protobuf:"varint,2,req,name=lat_msg_id,json=latMsgId" json:"lat_msg_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DataReq) Reset()                    { *m = DataReq{} }
func (m *DataReq) String() string            { return proto.CompactTextString(m) }
func (*DataReq) ProtoMessage()               {}
func (*DataReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *DataReq) GetDuid() string {
	if m != nil && m.Duid != nil {
		return *m.Duid
	}
	return ""
}

func (m *DataReq) GetLatMsgId() int64 {
	if m != nil && m.LatMsgId != nil {
		return *m.LatMsgId
	}
	return 0
}

type DataRes struct {
	Duid             *string `protobuf:"bytes,1,req,name=duid" json:"duid,omitempty"`
	MsgId            *int64  `protobuf:"varint,2,req,name=msg_id,json=msgId" json:"msg_id,omitempty"`
	MsgData          []byte  `protobuf:"bytes,3,req,name=msg_data,json=msgData" json:"msg_data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DataRes) Reset()                    { *m = DataRes{} }
func (m *DataRes) String() string            { return proto.CompactTextString(m) }
func (*DataRes) ProtoMessage()               {}
func (*DataRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *DataRes) GetDuid() string {
	if m != nil && m.Duid != nil {
		return *m.Duid
	}
	return ""
}

func (m *DataRes) GetMsgId() int64 {
	if m != nil && m.MsgId != nil {
		return *m.MsgId
	}
	return 0
}

func (m *DataRes) GetMsgData() []byte {
	if m != nil {
		return m.MsgData
	}
	return nil
}

type DataResBatchs struct {
	DataBatchs       []*DataRes `protobuf:"bytes,1,rep,name=data_batchs,json=dataBatchs" json:"data_batchs,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *DataResBatchs) Reset()                    { *m = DataResBatchs{} }
func (m *DataResBatchs) String() string            { return proto.CompactTextString(m) }
func (*DataResBatchs) ProtoMessage()               {}
func (*DataResBatchs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *DataResBatchs) GetDataBatchs() []*DataRes {
	if m != nil {
		return m.DataBatchs
	}
	return nil
}

// 外部调用rpc协议
// 推送给设备的信息
type PushDeviceReq struct {
	Duid             *string `protobuf:"bytes,1,req,name=duid" json:"duid,omitempty"`
	MsgData          []byte  `protobuf:"bytes,2,req,name=msg_data,json=msgData" json:"msg_data,omitempty"`
	ExpireTime       *int32  `protobuf:"varint,3,req,name=expire_time,json=expireTime" json:"expire_time,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PushDeviceReq) Reset()                    { *m = PushDeviceReq{} }
func (m *PushDeviceReq) String() string            { return proto.CompactTextString(m) }
func (*PushDeviceReq) ProtoMessage()               {}
func (*PushDeviceReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *PushDeviceReq) GetDuid() string {
	if m != nil && m.Duid != nil {
		return *m.Duid
	}
	return ""
}

func (m *PushDeviceReq) GetMsgData() []byte {
	if m != nil {
		return m.MsgData
	}
	return nil
}

func (m *PushDeviceReq) GetExpireTime() int32 {
	if m != nil && m.ExpireTime != nil {
		return *m.ExpireTime
	}
	return 0
}

// 返回的结果
type PushDeviceRes struct {
	Duid             *string `protobuf:"bytes,1,req,name=duid" json:"duid,omitempty"`
	Result           *int32  `protobuf:"varint,2,req,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PushDeviceRes) Reset()                    { *m = PushDeviceRes{} }
func (m *PushDeviceRes) String() string            { return proto.CompactTextString(m) }
func (*PushDeviceRes) ProtoMessage()               {}
func (*PushDeviceRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *PushDeviceRes) GetDuid() string {
	if m != nil && m.Duid != nil {
		return *m.Duid
	}
	return ""
}

func (m *PushDeviceRes) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

// 批量推送设备的消息
type PushDevBatchsReq struct {
	Batchs           []*PushDeviceReq `protobuf:"bytes,1,rep,name=batchs" json:"batchs,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *PushDevBatchsReq) Reset()                    { *m = PushDevBatchsReq{} }
func (m *PushDevBatchsReq) String() string            { return proto.CompactTextString(m) }
func (*PushDevBatchsReq) ProtoMessage()               {}
func (*PushDevBatchsReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *PushDevBatchsReq) GetBatchs() []*PushDeviceReq {
	if m != nil {
		return m.Batchs
	}
	return nil
}

type PushDevBatchsRes struct {
	BatchsResult     []*PushDeviceRes `protobuf:"bytes,1,rep,name=batchs_result,json=batchsResult" json:"batchs_result,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *PushDevBatchsRes) Reset()                    { *m = PushDevBatchsRes{} }
func (m *PushDevBatchsRes) String() string            { return proto.CompactTextString(m) }
func (*PushDevBatchsRes) ProtoMessage()               {}
func (*PushDevBatchsRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *PushDevBatchsRes) GetBatchsResult() []*PushDeviceRes {
	if m != nil {
		return m.BatchsResult
	}
	return nil
}

func init() {
	proto.RegisterType((*DevStat)(nil), "protol.DevStat")
	proto.RegisterType((*DevOffline)(nil), "protol.DevOffline")
	proto.RegisterType((*DevOnline)(nil), "protol.DevOnline")
	proto.RegisterType((*DevsAlive)(nil), "protol.DevsAlive")
	proto.RegisterType((*DataOccur)(nil), "protol.DataOccur")
	proto.RegisterType((*DataReq)(nil), "protol.DataReq")
	proto.RegisterType((*DataRes)(nil), "protol.DataRes")
	proto.RegisterType((*DataResBatchs)(nil), "protol.DataResBatchs")
	proto.RegisterType((*PushDeviceReq)(nil), "protol.PushDeviceReq")
	proto.RegisterType((*PushDeviceRes)(nil), "protol.PushDeviceRes")
	proto.RegisterType((*PushDevBatchsReq)(nil), "protol.PushDevBatchsReq")
	proto.RegisterType((*PushDevBatchsRes)(nil), "protol.PushDevBatchsRes")
}

func init() { proto.RegisterFile("ipc_push.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 386 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x51, 0x4f, 0x8f, 0x93, 0x40,
	0x14, 0xcf, 0x52, 0x4b, 0x97, 0x47, 0xab, 0x66, 0x92, 0x35, 0x98, 0x18, 0x97, 0xcc, 0x89, 0x8b,
	0x8d, 0xf1, 0xe8, 0xc6, 0x98, 0x1a, 0x2e, 0x1e, 0xb4, 0x66, 0xd6, 0xab, 0x99, 0xcc, 0xc2, 0x6b,
	0x3b, 0xc9, 0x40, 0x91, 0x19, 0x88, 0x1f, 0xdf, 0xcc, 0x30, 0x35, 0x62, 0xa9, 0x7b, 0x82, 0xf7,
	0xf8, 0xfd, 0x7d, 0xc0, 0x53, 0xd9, 0x14, 0xbc, 0xe9, 0xf4, 0x61, 0xdd, 0xb4, 0x47, 0x73, 0x24,
	0xa1, 0x7b, 0x28, 0xfa, 0x01, 0x16, 0x39, 0xf6, 0xf7, 0x46, 0x18, 0x42, 0xe0, 0x49, 0xd9, 0xc9,
	0x32, 0xb9, 0x4a, 0x83, 0x2c, 0x62, 0xee, 0x9d, 0xbc, 0x86, 0x58, 0x09, 0x6d, 0x78, 0xa5, 0xf7,
	0x5c, 0x96, 0x49, 0x90, 0x06, 0xd9, 0x8c, 0x45, 0x76, 0xf5, 0x45, 0xef, 0x3f, 0x97, 0x34, 0x05,
	0xc8, 0xb1, 0xdf, 0xee, 0x76, 0x4a, 0xd6, 0x38, 0xa5, 0x40, 0x3f, 0x42, 0x64, 0x11, 0xf5, 0x25,
	0xc0, 0xa3, 0x16, 0x3f, 0x9c, 0x80, 0xde, 0x28, 0xd9, 0x23, 0x59, 0x03, 0x94, 0xd8, 0xf3, 0xa3,
	0x93, 0x4b, 0xae, 0xd2, 0x59, 0x16, 0xbf, 0x7b, 0x36, 0x54, 0x52, 0x6b, 0x5f, 0x84, 0x45, 0xe5,
	0x1f, 0xc3, 0x14, 0x96, 0x35, 0x1a, 0x6e, 0x64, 0x85, 0x5c, 0x63, 0xe1, 0xd4, 0xe7, 0x0c, 0x6a,
	0x34, 0xdf, 0x65, 0x85, 0xf7, 0x58, 0xd0, 0x5b, 0x88, 0x72, 0x61, 0xc4, 0xb6, 0x28, 0xba, 0x76,
	0xb2, 0xc0, 0x1d, 0x2c, 0x2c, 0x80, 0xe1, 0xcf, 0xc9, 0xf8, 0xaf, 0x00, 0x94, 0xf8, 0x27, 0xfd,
	0xb5, 0x12, 0x3e, 0xfc, 0xf6, 0x44, 0xd6, 0x93, 0xe4, 0x1b, 0x08, 0x47, 0xc4, 0x79, 0x65, 0x59,
	0xe4, 0x25, 0x5c, 0xdb, 0x75, 0x29, 0x8c, 0x48, 0x66, 0x69, 0x90, 0x2d, 0xd9, 0xa2, 0xd2, 0x7b,
	0x2b, 0x44, 0x37, 0xb0, 0xf2, 0x82, 0x9f, 0x84, 0x29, 0x0e, 0x9a, 0xbc, 0x85, 0xd8, 0xe2, 0xf8,
	0x83, 0x1b, 0xcf, 0x4e, 0x32, 0x60, 0x19, 0x58, 0xcc, 0xc0, 0xa0, 0x1c, 0x56, 0xdf, 0x3a, 0x7d,
	0xc8, 0xb1, 0x97, 0x05, 0x5e, 0xaa, 0xf5, 0x77, 0x84, 0x60, 0x14, 0x81, 0xdc, 0x42, 0x8c, 0xbf,
	0x1a, 0xd9, 0xa2, 0x3b, 0xab, 0x0b, 0x38, 0x67, 0x30, 0xac, 0xec, 0x55, 0xe9, 0xdd, 0xd8, 0x60,
	0xba, 0xfa, 0x0b, 0x08, 0x5b, 0xd4, 0x9d, 0x32, 0xfe, 0x9f, 0xf8, 0x89, 0x6e, 0xe0, 0xb9, 0x27,
	0x0f, 0x71, 0x6d, 0xc0, 0x37, 0x10, 0x8e, 0xea, 0xdd, 0x9c, 0xea, 0x8d, 0x7a, 0x30, 0x0f, 0xa2,
	0x5f, 0xcf, 0x24, 0x34, 0x79, 0x0f, 0xab, 0xe1, 0x2b, 0xf7, 0xae, 0xff, 0x51, 0xd2, 0x6c, 0xf9,
	0x70, 0x22, 0x76, 0xca, 0xfc, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x14, 0x29, 0x81, 0x03, 0x3c, 0x03,
	0x00, 0x00,
}
